#!/bin/bash
set -o nounset -o errexit -o pipefail

NODE_SENV="${APP_ENV:-default}"
base_name="$(basename "$0")"
case "$base_name" in
  task-*) NODE_SENV="${base_name#task-}" ;;
esac
export NODE_SENV
if type volta >/dev/null 2>&1
then
  volta="$(type -p volta)"
else
  # Releases · volta-cli/volta https://github.com/volta-cli/volta/releases
  ver=2.0.1
  bin_dir="$PWD"/.bin
  cmd_name=volta
  cmd_path="$bin_dir/${cmd_name}@${ver}"
  if ! test -x "$cmd_path"
  then
    case "$(uname -s)" in
      Linux*) os=linux;;
      Darwin*) os=macos;;
      *) exit 1;;
    esac
    url=https://github.com/volta-cli/volta/releases/download/v${ver}/volta-${ver}-${os}.tar.gz
    curl --location "$url" | tar -xz --directory="$bin_dir" "volta"
    mv "$bin_dir/volta" "$cmd_path"
    chmod +x "$cmd_path"
  fi
  volta="$cmd_path"
fi
exec "$volta" run node -- "$(dirname "$(readlink -f "$0")")"/task.mjs "$@"
