#!/bin/bash
set -o nounset -o errexit -o pipefail

NODE_SENV="${APP_ENV:-default}"
base_name="$(basename "$0")"
case "$base_name" in
  task-*) NODE_SENV="${base_name#task-}" ;;
esac
export NODE_SENV
if type volta > /dev/null 2>&1
then
  cmd_path="$(type -p volta)"
else
  # Releases · volta-cli/volta https://github.com/volta-cli/volta/releases
  cmd_base=volta
  ver=2.0.1

  bin_dir="$PWD"/.bin
  cmd_path="$bin_dir/${cmd_base}@${ver}"
  if ! test -x "$cmd_path"
  then
    case "$(uname -s)" in
      Linux*) os=linux;;
      Darwin*) os=macos;;
      *) exit 1;;
    esac
    case "$(uname -m)" in
      x86_64) osArch="$os";;
      arm64) osArch="${os}-arm";;
      *) exit 1;;
    esac
    url=https://github.com/volta-cli/volta/releases/download/v${ver}/volta-${ver}-${osArch}.tar.gz
    curl --location "$url" | tar -xz --directory="$bin_dir" $cmd_base
    mv "$bin_dir/$cmd_base" "$cmd_path"
    chmod +x "$cmd_path"
  fi
fi
exec "$cmd_path" run node -- "$(dirname "$(readlink -f "$0")")"/task.mjs "$@"
