#!/bin/bash
set -o nounset -o errexit -o pipefail

NODE_SENV="${APP_ENV:-default}"
base_name="$(basename "$0")"
case "$base_name" in
  task-*) NODE_SENV="${base_name#task-}" ;;
esac
export NODE_SENV
exec node "$(dirname "$(readlink -f "$0")")"/task.mjs "$@"
