#!/bin/bash
set -o nounset -o errexit -o pipefail

APP_ENV="${APP_ENV:-undefined}"
base_name="$(basename "$0")"
case "$base_name" in
  task-*) APP_ENV="${base_name#task-}" ;;
esac
export APP_ENV
exec node "$(dirname "$(readlink -f "$0")")"/task.js "$@"
